### ISSUE TITLE
Dashboard is returning multiple records on a singular query

### ISSUE THREAD

**Issue by KenSuenobu** [KenSuenobu/curb#106]
```[Nest] 549331  - 01/01/2024, 10:52:44 PM   ERROR [ExceptionsHandler] Multiple rows were not expected.
QueryResultError: Multiple rows were not expected.
    at Query.<anonymous> (/home/kenji/curb/curb-db/node_modules/pg-promise/lib/query.js:197:41)
    at Query.handleReadyForQuery (/home/kenji/curb/curb-db/node_modules/pg/lib/query.js:139:14)
    at Client._handleReadyForQuery (/home/kenji/curb/curb-db/node_modules/pg/lib/client.js:312:19)
    at Connection.emit (node:events:517:28)
    at /home/kenji/curb/curb-db/node_modules/pg/lib/connection.js:117:12
    at Parser.parse (/home/kenji/curb/curb-db/node_modules/pg-protocol/src/parser.ts:104:9)
    at Socket.<anonymous> (/home/kenji/curb/curb-db/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:335:12)
    at readableAddChunk (node:internal/streams/readable:308:9)```

**Comment by KenSuenobu** [comment]
This was because the data was returning multiple years' worth of data.  This has been fixed.
